### ISSUE TITLE
How to display upload records?

### ISSUE THREAD

**Issue by Zhenbin24** [PX4/flight_review#102]
## I added all the public logs，eg：
![qq 20180408153414](https://user-images.githubusercontent.com/33947214/38464622-5b0ea088-3b43-11e8-8b43-6e5862ffa19b.png)

## But the browse page does not have any data?
![qq 20180408153339](https://user-images.githubusercontent.com/33947214/38464650-c0084624-3b43-11e8-90fe-2a01a5c67c72.png)
@bkueng @LorenzMeier

**Comment by bkueng** [comment]
How did you add the logs? Via upload form?
What is the console output?
