### ISSUE TITLE
File format conversion

### ISSUE THREAD

**Issue by Zhenbin24** [PX4/flight_review#105]
@bkueng @mrpollo @dagar @LorenzMeier @anassinator  I have a bin file for the flight log, how can I convert the ulog file to this project type？

**Comment by bkueng** [comment]
How did you create the bin file?

**Comment by Zhenbin24** [comment]
@bkueng The data written by the drone during its flight is exactly the one-chip computer

**Comment by bkueng** [comment]
If you use a the default logger, just rename the bin file to `.ulg`, and if not you are using an incompatible logger and there is no way to convert it.

**Comment by MaEtUgR** [comment]
Issue about an ardupilot _bin file_ with 2 hours time difference: https://github.com/PX4/flight_review/issues/106
Related?

**Comment by Zhenbin24** [comment]
@MaEtUgR  yea ，We are looking for good solutions for ardupilot。
