### ISSUE TITLE
Voltage should be plotted for all rails (including 5V and 3.3V)

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/flight_review#112]
The voltage plots should also have the 5V and 3.3V rails:

https://review.px4.io/plot_app?log=c2542936-0513-47fc-b1e9-1ff5c44c832e#Nav-Power

**Comment by bkueng** [comment]
Done in https://github.com/PX4/flight_review/commit/5277359da197cf71f1a65116a66bd110365e9ad4
