### ISSUE TITLE
Local Instance of Flight Review Doesn't Accept Uploaded Logs

### ISSUE THREAD

**Issue by keenanjohnson** [PX4/flight_review#115]
I'm attempting to run the flight review program locally and I can't quite get it to accept any logs.

I'm running the "serve.py" script.

It serves the splash screen fine.

However, when I attempt to upload a file, I get the following:

![image](https://user-images.githubusercontent.com/2559382/41824951-b1ea0cf0-77cd-11e8-8b02-9b95419f14df.png)

**Comment by keenanjohnson** [comment]
Actually I was able to resolve this by installing ATLAS

`sudo apt-get install libatlas-base-dev`

Perhaps the readme can be documented to include this dependency?

**Comment by bkueng** [comment]
Thanks I'll add it. Are you on ubuntu 18.04?
According to [this](https://packages.ubuntu.com/bionic/amd64/libatlas3-base/filelist), `libatlas3-base` is the right package to install.

**Comment by keenanjohnson** [comment]
I was attempting to run this on a raspbian image actually. Perhaps everyone else is running this in ubuntu, so it's not an issue?

**Comment by bkueng** [comment]
No, it should work on all (major) distros, that's why I was asking (I'm using it on Fedora for instance).
I updated the instructions in https://github.com/PX4/flight_review/commit/a45774b7a42233e21a6b8ac3327c144e6dc6385a, thanks
