### ISSUE TITLE
Attempting to add custom plot to local instance

### ISSUE THREAD

**Issue by keenanjohnson** [PX4/flight_review#116]
Hello there.

I'm attempting to add a custom plot to a local instance of this application.

I simply added this section of code to configured_plots.py file, but it doesn't seem to have added the plot.

Does anyone know what I am missing?

```
data_plot = DataPlot(data, plot_config, 'esc_status_0',
                     y_axis_label='Current (A)', title='Motor Currents',
                     plot_height='small', changed_params=changed_params,
                     x_range=x_range)
data_plot.add_graph(['esc[0].esc_current'], colors3, ['mtr1'])
plot_flight_modes_background(data_plot, flight_mode_changes, vtol_states)

if data_plot.finalize() is not None: plots.append(data_plot)
```

**Comment by keenanjohnson** [comment]
The "data" object doesn't appear to have an object for the esc_status_0 topic, even though I can see it in the flightplot desktop app.

Do I need to add that topic to another subscription list somewhere?

**Comment by bkueng** [comment]
Yes you need to add the topic here: https://github.com/PX4/flight_review/blob/master/plot_app/helper.py#L296

**Comment by keenanjohnson** [comment]
Got it. Thank you very much!
