### ISSUE TITLE
Maps view broken

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/flight_review#12]
This is from the SITL system, completely unreadable:

<img width="877" alt="screen shot 2016-12-13 at 09 31 31" src="https://cloud.githubusercontent.com/assets/1208119/21133190/f32f70b0-c117-11e6-93b7-3f502e935f26.png">

Zooming in and panning even worse:

<img width="857" alt="screen shot 2016-12-13 at 09 31 41" src="https://cloud.githubusercontent.com/assets/1208119/21133197/f7be3aee-c117-11e6-98ab-f4b2f9a0353b.png">

**Comment by LorenzMeier** [comment]
This log before applying any zooming:
http://logs.px4.io/plot_app?log=e322bc62-56e4-48e9-8dd3-136e2799e789

<img width="849" alt="screen shot 2016-12-13 at 21 35 58" src="https://cloud.githubusercontent.com/assets/1208119/21158104/3282fdae-c17c-11e6-9aff-c685ff706681.png">

**Comment by bkueng** [comment]
fixed in #14
