### ISSUE TITLE
Unable to view Ulog in Flight review

### ISSUE THREAD

**Issue by pranavn248** [PX4/flight_review#120]
I'm not able to view this [log](https://logs.px4.io/plot_app?log=2880461d-ff8f-4ae2-b359-60c6e5e5e97d) in flight review. I get the "Internal Server Error" when I try to upload and view it. Is there any way of viewing ulog files other than this?

**Comment by bkueng** [comment]
Thanks for the report, I fixed it in https://github.com/PX4/flight_review/commit/940e3ac633cc7f055acb0370a5c23d9b32e3705b.
