### ISSUE TITLE
Request: search + filters for public logs

### ISSUE THREAD

**Issue by dagar** [PX4/flight_review#121]
I don't know how viable this is, but I might as well ask.

From public flight reports only I'd like to be able to find all the logs from particular vehicles, airframes, flight controllers, versions of PX4 (specific commits and tags).

 - Vehicle UUID
 - Airframe
 - Hardware
 - Software version

 - basic filters to eliminate irrelevant logs (no takeoff or very short)

**Comment by bkueng** [comment]
Except for the last one this is already possible. Check out the search field.

**Comment by dagar** [comment]
Yes I tried that first, but assumed it only searched entries in the table. I wasn't able to get any results searching for vehicle UUID or git sha.

**Comment by bkueng** [comment]
You're right, looks like we did not have everything upstream yet.
