### ISSUE TITLE
the height of the plane in 3d view module

### ISSUE THREAD

**Issue by yukun2016** [PX4/flight_review#125]
hello,i have a question about the height display in 3d module.
is that designed by the "local z" data ? or the "altitude of gps/baro" ? or the "thrust"?

thanks and best wishes

**Comment by bkueng** [comment]
Hi
It's the GPS altitude, but it is offset by the ground elevation at the takeoff location (it assumes the log starts from the ground), because I had cases where the GPS altitude was below the ground, and then you would not see the trajectory and the vehicle.
Does that help?

**Comment by yukun2016** [comment]
thanks for your reply,i saw the three_d.py file.so i think it should be the gps height.i met a problem about the height or the airplane.but when i saw the 3d view,i saw it can identify the height change like the real fly. so i change the param ekf2_hgt_mode in ekf2  from baro to gps, the height of my airplane change good.
best wishes
