### ISSUE TITLE
estimator status missing

### ISSUE THREAD

**Issue by dagar** [PX4/flight_review#126]
Is there a reason estimator status seems to be missing in recent logs?

Example - https://logs.px4.io/plot_app?log=a58b6886-2b27-41c8-830f-e96ce6d28266

The actual log contains the relevant messages.

**Comment by bkueng** [comment]
nan_flags got removed from the Firmware. Fixed in https://github.com/PX4/flight_review/commit/b20eecd896724611b1602796ed00254127352f37.

**Comment by dagar** [comment]
Thanks!
