### ISSUE TITLE
Internal server error in browse page

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/flight_review#13]
@bkueng The system currently reports an internal server error on the browse tab:
http://logs.px4.io/browse

This was potentially the lag log that got uploaded and might be related to the breakage (or one of the SITL logs):

http://logs.px4.io/plot_app?log=e322bc62-56e4-48e9-8dd3-136e2799e789

**Comment by bkueng** [comment]
fixed in https://github.com/PX4/flight_review/commit/1f3b2d745310d3a85bf7716d24f02ff7ae096a5e
