### ISSUE TITLE
Add TECS plots

### ISSUE THREAD

**Issue by RomanBapst** [PX4/flight_review#130]
Would be useful to have a few plots for TECS

**Comment by moreba1** [comment]
5 days ago 
Hi

it is useful to see airspeed setpoint (airspeed_sp) and filtered airspeed (airspeed_filtered) in airspeed plot .

and there is need to see height_rate and height_rate_setpoint for fixedwings and vtol drones

**Comment by moreba1** [comment]
@bkueng 
could you add this plots?

**Comment by bkueng** [comment]
Can you do it and create a pull request? Alternatively send me a log?

**Comment by moreba1** [comment]
no , i can not do it , sample log :
https://review.px4.io/plot_app?log=b6146ff1-7a47-4259-a6ed-be9f05e1d172

**Comment by bkueng** [comment]
I added the Height Rate in https://github.com/PX4/flight_review/commit/6ebb1a59762ee0d30f596d2317f7140730179bcc:

![bokeh_plot](https://user-images.githubusercontent.com/281593/63914917-f3dd7d80-ca34-11e9-9e34-8f664aea9ef6.png)

**Comment by moreba1** [comment]
Thank you . if it is possible add airspeed setpoint and filtered airspeed an airspeed tab .

**Comment by bkueng** [comment]
We have that now, let me know if anything is missing
