### ISSUE TITLE
Estimator type incorrect

### ISSUE THREAD

**Issue by jgoppert** [PX4/flight_review#15]
I'm testing a new estimator here (https://github.com/PX4/Firmware/pull/6045), and it always shows the logs as EKF2.

http://logs.px4.io/plot_app?log=8d8211a2-93cb-4b22-86b3-ee04730e51e5

Do I need to set a field somewhere?

**Comment by mhkabir** [comment]
I think the SYS_MC_EST_GROUP param.

**Comment by bkueng** [comment]
Exactly. And it's parsed here: https://github.com/PX4/pyulog/blob/master/pyulog/px4.py#L52

**Comment by bkueng** [comment]
Done in Firmware https://github.com/PX4/Firmware/pull/6130
