### ISSUE TITLE
Meaning of unlabeled red area instead of flight mode

### ISSUE THREAD

**Issue by flochir** [PX4/flight_review#150]
The Flight Review plot of a recent test flight shows an unlabeled, red area as "flight mode" shortly after a switch from mission to altitude mode (see image). 

I can't find any information on this, what does it mean?
![flight_review_red_area_flight_mode](https://user-images.githubusercontent.com/38494856/50054626-f06ec400-013b-11e9-8a61-2c41a70dd60a.png)

**Comment by bkueng** [comment]
It's Manual mode.
