### ISSUE TITLE
GPS track and x / y plot not shown when there is RTK fix

### ISSUE THREAD

**Issue by shylent** [PX4/flight_review#155]
For some reason, log files that have RTK fix in them produce neither a map with GPS track, nor a x / y plot. When there is no RTK fix available, everything works as intended. Example of "non-working" log file: https://review.px4.io/plot_app?log=89fe82b4-4fa5-4b8c-aadb-1d57bc9160e2

**Comment by bkueng** [comment]
The log does not contain the `vehicle_global_position` topic, and also no `vehicle_attitude` message. It looks like ekf did not initialize for some reason, and you need to investigate that.
This is not a plotting issue, but a lack of data in the log.
