### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by SelimOzel** [PX4/flight_review#157]
How do we deploy the project to other computers on a network/internet? I have it setup on my local Mac but it seems to be serving only to itself and does not respond to external requests.

Best,
Selim

**Comment by bkueng** [comment]
You can use the `--address` argument, and you probably also have to pass `--allow-websocket-origin=*`.

**Comment by SelimOzel** [comment]
Thanks!! I will check these out tomorrow.

**Comment by mrischmu** [comment]
Hi,  
Any idea on which option to start?
Thanks
