### ISSUE TITLE
Add ground truth attitude and position for sitl

### ISSUE THREAD

**Issue by jgoppert** [PX4/flight_review#16]
Really need this for: https://github.com/PX4/sitl_gazebo/pull/82

Will try to do a PR if you don't have time.

**Comment by bkueng** [comment]
Sorry, took a bit longer, fixed in #19. The server is now updated as well.

**Comment by jgoppert** [comment]
@bkueng Thanks again. Kind of hard to compare vs GPS any chance of getting all of the xy data on one plot, or any thoughts on that?

**Comment by bkueng** [comment]
My intention was not to overload this plot. But sure, I can add it to the existing plot as well.
