### ISSUE TITLE
Display groundspeed 

### ISSUE THREAD

**Issue by moreba1** [PX4/flight_review#164]
Hi

I need to see ground speed of UAV . currently just display horizontal and vertical speed components

**Comment by bkueng** [comment]
It's already plotted if there is airspeed data: https://github.com/PX4/flight_review/blob/master/plot_app/configured_plots.py#L485.

**Comment by moreba1** [comment]
yes , it plot airspeed but does not plot groundspeed value.

**Comment by bkueng** [comment]
Can you provide the log?

**Comment by moreba1** [comment]
sample  log:
https://review.px4.io/plot_app?log=f0b49689-61ff-4cdd-b4f7-240c5d966bc6

parameter that must be plotted:  vehicle_gps_position_0.vel_m_s

**Comment by bkueng** [comment]
Ok, I added it in https://github.com/PX4/flight_review/commit/671f7ad2d1a3451baf85b55010dc65527b825ad6.

**Comment by moreba1** [comment]
Thank you
