### ISSUE TITLE
matplotlib no longer supports Python 3.5

### ISSUE THREAD

**Issue by cclauss** [PX4/flight_review#174]
See flake8 changes in #173 --> https://travis-ci.org/PX4/flight_review/jobs/588378671#L280

@bkueng @dagar Do we drop support for Python 3.5 or do we [__matplotlib >= 3.0.3__](https://github.com/PX4/flight_review/blob/master/Pipfile#L16) ?

**Comment by bkueng** [comment]
I was considering removing `pipenv`, since I'm generally not convinced by it. One thing it did is adding a `matplotlib==3.1.0` requirement, but none of the code actually requires it.
So we shouldn't drop python 3.5 but adjust the requirements.

**Comment by cclauss** [comment]
Agreed.  I do not get the pipenv workflow.
