### ISSUE TITLE
download log file not parameters

### ISSUE THREAD

**Issue by vivienJ** [PX4/flight_review#18]
Hello,
When I try to download parameters from a log, the .ulog file is downloaded not the paramters file.
This worked few days ago. Maybe since the KLM track download function ?

Thank for this very usefull flight log analysis.

Vivien

**Comment by bkueng** [comment]
Hi Vivien
Indeed. Thanks, it's fixed in https://github.com/PX4/flight_review/commit/07f0a73c306a3356d7b630787875010a0370622e
