### ISSUE TITLE
feature request: Displaying camera trigger locations on map 

### ISSUE THREAD

**Issue by moreba1** [PX4/flight_review#180]
Hi

I need to display camera trigger locations on map for troubleshooting and improving px4 code.

**Comment by bkueng** [comment]
We had this for KML (and it's still there if you download the KML file): https://github.com/PX4/flight_review/blob/master/tornado_handlers/download.py#L106, but moved away from that for the map, so you (or someone) will need to add it here: https://github.com/PX4/flight_review/blob/master/plot_app/templates/index.html#L26.
