### ISSUE TITLE
Ground truth plot using GPS data instead

### ISSUE THREAD

**Issue by jgoppert** [PX4/flight_review#20]
See this plot:

http://logs.px4.io/plot_app?log=b3dc79d6-6c5a-4178-a459-fbc8291d62b8

Clearly the ground truth is just the GPS since there is so much random noise in it.

**Comment by bkueng** [comment]
This is what it plots: https://github.com/PX4/flight_review/blob/master/plot_app/configured_plots.py#L166
I don't see anything wrong with that. It must be the data.

**Comment by jgoppert** [comment]
weird, will check when i get a chance

**Comment by kaklik** [comment]
This should be closed I think, to maintain focus on the relevant issues. :)
