### ISSUE TITLE
Plot airspeed

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/flight_review#21]
@bkueng Now that we start to have fixed wing logs we should try to plot airspeed vs. ground speed:
http://review.px4.io/plot_app?log=68e01eee-23ba-43ec-95d1-4e87b47213b8

**Comment by bkueng** [comment]
Done in https://github.com/PX4/flight_review/commit/68237ef6689063204334d4431f593c7e12ad92fd

This is for the log above:
![bokeh_airspeed](https://cloud.githubusercontent.com/assets/281593/23253100/8ed4e9b8-f9b3-11e6-83fd-8966128eb253.png)

And this is SITL:
![bokeh_airspeed_sitl_vtol](https://cloud.githubusercontent.com/assets/281593/23253111/996a2370-f9b3-11e6-9f9d-5e1c44f9fa1d.png)
