### ISSUE TITLE
Plots hard to analyze for colorblind people

### ISSUE THREAD

**Issue by marcojob** [PX4/flight_review#212]
For colorblind people it's almost impossible to distinguish red and green plots in certain cases; would be nice if there was a way to change all plots color to a different set. Example where it's hard to see the difference between lines:
![Screenshot from 2021-03-28 21-16-29](https://user-images.githubusercontent.com/44396071/112764972-313c2f80-900b-11eb-91c0-8be40031b273.png)

**Comment by bkueng** [comment]
Can you make a specific suggestion?

**Comment by marcojob** [comment]
Sure, there is plenty of colorblind friendly palettes, i.e:
<img width="1079" alt="zX6EV" src="https://user-images.githubusercontent.com/44396071/112800744-5911ae80-9070-11eb-9642-7c3eb422a74e.png">
I think it could be a nice addition for the enhancement backlog (if this exists) since around 8% of men and 0.5% of women are affected by some degree of color blindness.

**Comment by bkueng** [comment]
Sure, I have no problem changing colors, it's just that everything needs to be checked to still work and harmonize.
I can do that when I find the time.

**Comment by KarthiAru** [comment]
@bkueng Any update on this? I'm colorblind too and find it hard to distinguish red and green lines. 
Where are the config for the color codes specified? In the meantime, I can make the changes in my local server.

**Comment by KarthiAru** [comment]
I updated the colors in config.py in my local based on the palette shared by @marcojob. The combination of colors also matters. I had to use a combination of a darker & a lighter color for the two primary colors to distinguish better.

<img width="752" alt="image" src="https://github.com/user-attachments/assets/f4cc8d50-2d65-4439-a4d5-751c86dd08d7">

```
# Vermilion: #d55e00
# Yellow: #f0e442
# Blue: #0072b2
# Blue Green: #009e73
# Orange: #e69f00
# Sky Blue: #56b4e9
# Pale Violet: #cc79a7
# Black: #000000

plot_color_blue = '#56b4e9' # original: #2877a2, #3539e0
plot_color_red = '#d55e00' # original: #e0212d

color_gray = '#464646'
colors8 = ['#d55e00','#f0e442','#0072b2','#009e73','#f0e442','#56b4e9','#cc79a7','#000000']
colors3 = colors8[0:3]
colors2 = colors8[0:2] # for data to express: 'what it is' and 'what it should be'
```
