### ISSUE TITLE
500 Internal Server Error when uploading .ULG

### ISSUE THREAD

**Issue by FlyingFish136** [PX4/flight_review#219]
I am totally new to GitHub and have absolutely zero coding experience... However, for my Masters thesis project we have used a PX4 inside a light aircraft to record the GPS and telemetry data.

When I go to upload a .ulg file I get sent to this web address and given this server error - any ideas?

https://logs.px4.io/upload

![image](https://user-images.githubusercontent.com/85930671/122022595-a6273600-cdbe-11eb-8d81-f4a941d88372.png)

If it means anything, I'm on a Windows 10 machine using the latest MS Edge browser Version 91.0.864.48 (Official build) (64-bit)

**Comment by bkueng** [comment]
Hi. Can you provide the log file? You can also PM me if you prefer.

**Comment by FlyingFish136** [comment]
I can't seem to upload the file for some reason. I even sent it to a compressed ZIP, is this a GitHub thing I'm unaware of? I made a copy of the file and opened it in Notepad++ where as far as I can tell it has recorded data, whether or not it's all garbage I of course don't know. Shall I email you the file @bkueng? :)

**Comment by bkueng** [comment]
Yes. But first try again to upload again, there was actually an issue on the server.
