### ISSUE TITLE
Altitude control mode color

### ISSUE THREAD

**Issue by dagar** [PX4/flight_review#22]
It's very difficult to see the dark gray altitude control section over a satellite map.

![image](https://cloud.githubusercontent.com/assets/84712/22997439/60d54e86-f3a0-11e6-9213-0c3822eebb5e.png)

![image](https://cloud.githubusercontent.com/assets/84712/22997460/7296f9bc-f3a0-11e6-9dc3-130c9554f304.png)

http://logs.px4.io/plot_app?log=4011b562-64a3-494e-8685-782414499d52

**Comment by bkueng** [comment]
Not easy to find another distinct color. How about this:

![flight_review_altitude_color1](https://cloud.githubusercontent.com/assets/281593/23226471/e9e171ba-f935-11e6-87af-38055f259c55.png)
![flight_review_altitude_color2](https://cloud.githubusercontent.com/assets/281593/23226473/edb444f2-f935-11e6-83db-435ff6a483dd.png)

**Comment by dagar** [comment]
Anything discernable over a satellite map works for me. Thanks!

**Comment by bkueng** [comment]
Done in https://github.com/PX4/flight_review/commit/7d385b03f1e4dc5700f3165b5a5791545acb02cc
