### ISSUE TITLE
Crazy large logging duration and flight time values affecting graph axes limits

### ISSUE THREAD

**Issue by czasz** [PX4/flight_review#222]
I am trying to analyze my flight data but the flight review tool shows astronomically large values for both the logging duration and flight time which in turn affects the graphs and makes it very difficult to analyze the data.

This is the first issue I see (the actual flight time is about 5 minutes):
![image](https://user-images.githubusercontent.com/58744259/127367934-2229aa78-8577-42b1-ba0d-a61d4bccd6ee.png)

This causes the graphs to look like this, which is very clearly driven by the incorrect log duration values:
![image](https://user-images.githubusercontent.com/58744259/127368198-f9a69b2c-adba-4a59-a58c-b733fa7685cb.png)

However when I zoom in a crazy amount, everything looks fine:
![image](https://user-images.githubusercontent.com/58744259/127368330-c1a24566-79ca-47cd-ac9d-6cfc54f10768.png)

Does anyone know the cause of this issue/bug? I'm not sure if this is a problem on the flight review side or on PX4's side.

**Comment by bkueng** [comment]
This generally happens when a timestamp is invalid. So on the PX4 side. You can look at the raw data to find the topic (convert to csv or instrument pyulog).

**Comment by czasz** [comment]
Thanks @bkueng that was indeed the issue, I dug into the firmware source code and was able to find the problem.

**Comment by bkueng** [comment]
I take it that was something in your code, and not upstream?

**Comment by czasz** [comment]
Yes that's correct
