### ISSUE TITLE
Public log file download issue

### ISSUE THREAD

**Issue by abhishekgs1** [PX4/flight_review#230]
Hi 
I am unable to download the public logfile from the code provided 
It seems that DB API is not responding
Can you please check and update if I can download the files from the script

Please find the error attached below
![image](https://user-images.githubusercontent.com/93030186/157993879-513375d6-2b03-4fcd-a644-cbb83e6e73ed.png)

Regards
Abhishek

**Comment by bkueng** [comment]
Can you try again? The cache update takes a bit longer sometimes.

**Comment by abhishekgs1** [comment]
Hi I tried but still the error exists, also I tried to ping https://review.px4.io/dbinfo which is part of the code still I got the bad gateway error

![Error1](https://user-images.githubusercontent.com/93030186/158660822-b991e998-902e-4d01-840f-f172017a545e.PNG)
![Error2](https://user-images.githubusercontent.com/93030186/158660825-aa93ccc8-c1b1-41a1-a118-05cfb791ac2c.PNG)

**Comment by abhishekgs1** [comment]
Do you have any suggestions or other code to get this data?
if yes please share

**Comment by abhishekgs1** [comment]
> Can you try again? The cache update takes a bit longer sometimes.

**Comment by abhishekgs1** [comment]
> Can you try again? The cache update takes a bit longer sometimes.

**Comment by bkueng** [comment]
I cleaned up the db a bit, it's working for me again.

**Comment by bkueng** [comment]
Fixed in https://github.com/PX4/flight_review/commit/62b75900b78106b13e6f04faf7e1b5d37e117570
