### ISSUE TITLE
Ulg file upload fails - 500 Internal Server Error

### ISSUE THREAD

**Issue by bednarhonza** [PX4/flight_review#232]
Hello,
I'm facing an issue with uploading a .ulg log. It has already taken for an hour at least. I have tried also other logs, that used to upload without any issues.
![Screenshot from 2022-03-23 13-45-05](https://user-images.githubusercontent.com/17883198/159702251-5e3942fa-45bd-4012-b1ff-a62a89d4bf89.png)

Thanks!

**Comment by bkueng** [comment]
Hi
The server ran out of temporary storage, I cleaned it up.

**Comment by bednarhonza** [comment]
Thanks for the help!
