### ISSUE TITLE
Parse error on Orange Cube Test build

### ISSUE THREAD

**Issue by aksuns96** [PX4/flight_review#244]
**Issue**
Uploading orangecube_test builds of v1.13 to flight review returns the error "HTTP Error 400: Failed to parse the file. It is most likely corrupt."
This error does not occur on orangecube_default builds unless the mavlink console is enabled via Nuttx defconfig.
If mavlink console is enabled, upload returns with the same error.

**Comment by bkueng** [comment]
There was a problem with the console on H7, not sure if the fix made it into 1.13. Can you test with latest PX4 main?

In any case, this must be an issue with PX4 and not flight review. Please open an issue there if it persists with latest main.
