### ISSUE TITLE
Stats tab showing 504 Gateway timeout

### ISSUE THREAD

**Issue by junwoo091400** [PX4/flight_review#245]
## About
Trying to access https://logs.px4.io/stats results in the following error message after ~40 seconds of loading screen.

![image](https://user-images.githubusercontent.com/23277211/187925157-b33814fc-727e-43a9-9e5d-3a1270e907a9.png)

**Comment by bkueng** [comment]
Fixed in https://github.com/PX4/flight_review/commit/352dd3f9d2f2f300733f8562b28c1aeece7e2443
