### ISSUE TITLE
Question/Issue about Motor Outputs

### ISSUE THREAD

**Issue by danielhonies** [PX4/flight_review#248]
I have a VTOL with 10 Motors, 8 upwards, two forwards. Flight review only shows the first eight motor pwm outputs (all upwards and connected to main). Why are the other two not shown? is this an issue or expexted behaviour?

**Comment by bkueng** [comment]
Hi
Yes flight review sets the maxmimum to 8: https://github.com/PX4/flight_review/blob/main/app/plot_app/configured_plots.py#L577
I increased it in https://github.com/PX4/flight_review/commit/1640644404f7bee5982abee305c3e5bcffa0f7af.
