### ISSUE TITLE
Frequency analysis 

### ISSUE THREAD

**Issue by Stifael** [PX4/flight_review#25]
It would be beneficial to have fft function.

**Comment by dagar** [comment]
@Stifael which FFT plots would be worth including?

**Comment by RomanBapst** [comment]
@Stifael Can we close this? If you have high rate logging enabled you will get the spectrum of the actuator controls. And I think you always get the spectrum from the accelerometer.

**Comment by MaEtUgR** [comment]
@RomanBapst yes, close it, it's not specific and basic frequency plots are there by now.
