### ISSUE TITLE
Request: Converter for ulog -> .txt file

### ISSUE THREAD

**Issue by KrisFRS** [PX4/flight_review#262]
Hello,

The team that I work with would like to be able to analyze the data more freely and are hoping for a way to convert the flight logs into a text file.

Does the development team have something like this already or any recommendations on how to do this?

Thank you and have a nice day.

**Comment by julianoes** [comment]
I think you're looking for ulog2csv, see: https://github.com/PX4/pyulog/#convert-ulog-to-csv-files-ulog2csv
