### ISSUE TITLE
invalid start byte

### ISSUE THREAD

**Issue by afwilkin** [PX4/flight_review#266]
I am getting an invalid start byte a lot recently

https://discuss.px4.io/t/flight-review-file-corrupt-flight-core-v2/33516/8

I have seen this on pixhawk 6c and the Modalai flight core v2

**Comment by afwilkin** [comment]
It loads in plotjuggler just fine, which led me to think this is a Flight Review Issue

**Comment by bkueng** [comment]
> It loads in plotjuggler just fine, which led me to think this is a Flight Review Issue

It just means that PlotJuggler ignores the file corruption.

Let's continue the discussion on discuss.
