### ISSUE TITLE
Attribute Eror in testing_notebok.py when using bokeh 3.3.2

### ISSUE THREAD

**Issue by tarbaig** [PX4/flight_review#277]
Behavior
===

When running the ipython notebook using the dependencies from requirements.txt. cell 8 raises an atribute error:
```AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width```

Expected
===
No Error

Analysis
===
Bokeh 3.x use different parameter names, this can be fixed by changing ```plot_width``` to ```width```

**Comment by tarbaig** [comment]
I`ll probably prepare a pull request to address this and further issues with the notebook once I am done with fixing the problems.

**Comment by bkueng** [comment]
This works now from what I can tell
