### ISSUE TITLE
WSL with Ubuntu - make accesible for local network

### ISSUE THREAD

**Issue by diablo1281** [PX4/flight_review#283]
Hi,
after using online version of Flight Review, I decided to try run it locally. But after setup, I can only access it on local machine (localhost or IP of WSL). I can't find way to make it accessible on my local network. Any help would be appreciated! Thanks.

**Comment by bkueng** [comment]
Hi
You need to explicitly allow remote hosts by adding these flags: `--allow-websocket-origin=* --host=*` to `serve.py`
