### ISSUE TITLE
The entire service is single-threaded, so when uploading files, no other operations can be performed.

### ISSUE THREAD

**Issue by ThreeDogsAl** [PX4/flight_review#296]
The entire service is single-threaded, so when uploading files, no other operations can be performed.What should i do

**Comment by ThreeDogsAl** [comment]
![image](https://github.com/user-attachments/assets/e1ec770c-cf5f-4022-bb00-9006c5c555db)
I directly ran the server.py file. Then when uploading a file, as shown in the screenshot, if I tried to access the /upload page while the file was being uploaded, it would keep loading. Only after entering the /plot_app?log=6c1d2f41-a923-4e48-a02b-f55963457781 page would the /upload page in the other window finally load.

**Comment by ThreeDogsAl** [comment]
I've noticed the --num-procs parameter, but I'm using Windows.

**Comment by ThreeDogsAl** [comment]
> That is actually not correct. Requests are handled asynchronously. Even with a single thread, the tornado web server serves requests during an upload. In addition, the `serve.py` script allows to pass `--num-procs` to run multiple processes.

I've noticed the --num-procs parameter, but I'm using Windows.

**Comment by ThreeDogsAl** [comment]
![image](https://github.com/user-attachments/assets/6ffc9b67-e6ac-48ae-9029-eda9e56dabe5)
When I'm uploading a file, if I make a request to `/upload` at the same time, the `print("=================")` statement won't be executed at all.

**Comment by ThreeDogsAl** [comment]
@bkueng What should i do

**Comment by ThreeDogsAl** [comment]
I'm deploying it on Windows and directly starting the project with the script "server.py". There is the problem mentioned above. During the uploading process, I can't perform other operations, such as viewing the "/browse" interface or the "/upload" interface. Are there any additional configurations?&nbsp;


gs
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Beat ***@***.***&gt;; 
发送时间: 2024年12月5日(星期四) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PX4/flight_review] The entire service is single-threaded, so when uploading files, no other operations can be performed. (Issue #296)














 
That is actually not correct. Requests are handled asynchronously. Even with a single thread, the tornado web server serves requests during an upload.
 In addition, the serve.py script allows to pass --num-procs to run multiple processes.

**Comment by bkueng** [comment]
Sorry, but I cannot help you here, especially not with Windows. You might want to look into Tornado, and how it works on Windows.

**Comment by ThreeDogsAl** [comment]
@bkueng thanks. I am encountering the same issue on Linux: after uploading the .ulg file, other requests get blocked during the process of generating the plot.

**Comment by bkueng** [comment]
The plot generation might take some time depending on your cpu and log size. You can enable timing information here: https://github.com/PX4/flight_review/blob/main/app/config_default.ini#L29

**Comment by bkueng** [comment]
Closing, you're welcome to improve plot loading time if you find anything.
