### ISSUE TITLE
download rate too slow

### ISSUE THREAD

**Issue by EhsanZibaei** [PX4/flight_review#297]
Hi everyone,
I’m working on a research project focused on diagnosing UAV failures automatically using statistical methods. To support this, I need to download a large number of flight logs from [review.px4.io](http://review.px4.io/). However, the server seems to be limiting the download speed to 20 Kb/s.
![Screenshot from 2024-12-05 21-03-13](https://github.com/user-attachments/assets/57a09ca3-1f93-41d0-9cec-6fbc31263ebb)

Is this a common issue? Are there any alternative methods or tools to speed up the download process?

Thanks in advance for your help!

**Comment by bkueng** [comment]
That is indeed awfully slow. Download is generally not super fast, but in my experience at least 10x from what you see. Did you try on multiple occasions?
Are you using the download script from the repo?

**Comment by EhsanZibaei** [comment]
I tried again today, and this time it was faster. around 3 Mb/s. Maybe it was a server issue

**Comment by bkueng** [comment]
Ok good to know, thanks. There's not much I can do here though.
