### ISSUE TITLE
show VTOL state

### ISSUE THREAD

**Issue by dagar** [PX4/flight_review#32]
It's not clear when a VTOL is in MC or FW mode.
http://review.px4.io/plot_app?log=d22eb960-a60c-44de-a643-11070a868408

Could we add lines indicating any change in vtol state (MC, TRANSITION, FW), or would that be too much clutter?

**Comment by bkueng** [comment]
Do you mean all plots? Probably, especially with parameter changes.
I think it would also be useful to show the other actuator controls & outputs.

I'll do some tests to see how it looks.

**Comment by dagar** [comment]
https://github.com/PX4/flight_review/pull/33
