### ISSUE TITLE
Display geotags on map

### ISSUE THREAD

**Issue by mhkabir** [PX4/flight_review#36]
@bkueng It would be great if we can display the geotag points on the map so that we know where the camera was triggered. They are currently logged in the [`camera_capture` message](https://github.com/PX4/Firmware/blob/master/msg/camera_capture.msg).

![image](https://cloud.githubusercontent.com/assets/5557676/26292963/9893c28e-3eba-11e7-89e7-55c986df5874.png)

Log : https://drive.google.com/file/d/0B3WIncZkmRb6Y0piUms0RjkyeTQ/view?usp=sharing

**Comment by mhkabir** [comment]
This would also help people using suboptimal camera setups which miss triggers which PX4 did command.

**Comment by bkueng** [comment]
Good idea. I'll do that when I get a log

**Comment by mhkabir** [comment]
@bkueng Here you go : https://drive.google.com/file/d/0B3WIncZkmRb6Y0piUms0RjkyeTQ/view?usp=sharing

**Comment by bkueng** [comment]
Done:
![flight_review_camera_trigger](https://cloud.githubusercontent.com/assets/281593/26311660/63eb8ec2-3f05-11e7-9ac5-03107fef1397.png)

**Comment by mhkabir** [comment]
Amazing, thanks!
