### ISSUE TITLE
Graphs should have the same time dimension

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/flight_review#38]
Currently the graphs do not align in time - e.g. if messages from one topic stop updating it crops the graph and they are unaligned. All graphs should start and stop at the min and max times for which we have any data, not just the topic they are graphing.

The current state can make crash analysis quite confusing, because you carefully need to read the time labels.

**Comment by bkueng** [comment]
Done in https://github.com/PX4/flight_review/commit/6851ec230ec9dec381e9ad49e19ffc2af2c8ae6a
