### ISSUE TITLE
estimator watchdog

### ISSUE THREAD

**Issue by dagar** [PX4/flight_review#44]
From http://logs.px4.io/plot_app?log=00b0b048-39bd-45cd-910b-c3d54b0f39ad (https://github.com/PX4/Firmware/issues/7463)

Flight review estimator watchdog doesn't show anything.

![image](https://user-images.githubusercontent.com/84712/27496346-98b9b732-5823-11e7-9785-bd646fa6ab14.png)

This log has filter fault flags and innovation check flags.

[00b0b048-39bd-45cd-910b-c3d54b0f39ad.ulg (2).pdf](https://github.com/PX4/flight_review/files/1098770/00b0b048-39bd-45cd-910b-c3d54b0f39ad.ulg.2.pdf)

**Comment by bkueng** [comment]
Fixed in #45:
![flight_review_watchdog](https://user-images.githubusercontent.com/281593/27533366-98329558-5a63-11e7-9ab9-dc324dc0f539.png)
Turns out ekf2 uses different flags than LPE

**Comment by dagar** [comment]
Thanks!
