### ISSUE TITLE
Use S3 instead of local disk to store logs

### ISSUE THREAD

**Issue by mrpollo** [PX4/flight_review#47]
Drive costs on AWS are somewhat expensive, we should move our storage to S3, there's lots of python bindings for S3 nowadays, I'll submit a PR as soon as I can, or if there's anyone interested in helping just let me know I can set you up with S3

**Comment by bkueng** [comment]
Thanks. Please make sure we support both via config option.

**Comment by bkueng** [comment]
I reduced the disk size & removed old CI logs, feel free to re-open if still relevant.
