### ISSUE TITLE
peoblem of setup server

### ISSUE THREAD

**Issue by feilongfl** [PX4/flight_review#51]
i setup a server with ubuntu 16.04 lts,but it can not plot anything.in chrome dev console,it show me websocks not work,and console show me   
>list index out of range  
but i don't know where is wrong.can you give me some advice?thanks!

![screenshot 2017-07-26 at 12 36 43](https://user-images.githubusercontent.com/10269596/28604972-37f86328-7194-11e7-8e4a-b6e00e3a3c05.png)  
![screenshot 2017-07-26 at 12 52 06](https://user-images.githubusercontent.com/10269596/28604990-4cec3f98-7194-11e7-8cfd-b5ffa564a6f9.png)

**Comment by feilongfl** [comment]
i run server with the command 
```
./serve.py --port 8080 --allow-websocket-origin 10.1.51.135 --num-procs 0 
```

**Comment by bkueng** [comment]
Hi @feilongfl 

You can ignore the `list index out of range` errors, it just means that the log does not contain this data.

Can you try with:
```
./serve.py --port 8080 --allow-websocket-origin '*'
```
or:
```
./serve.py --port 8080 --allow-websocket-origin 10.1.51.135:8080
```

**Comment by feilongfl** [comment]
@bkueng thank you for reply. I have find the reason, it is my http proxy's error.
