### ISSUE TITLE
VTOL average speed 

### ISSUE THREAD

**Issue by sanderux** [PX4/flight_review#56]
@bkueng i see you added average speed. For VTOL it would be great to have average speed separated for MC and FW mode. The sum of these doesn't say much but individually they do

**Comment by bkueng** [comment]
Sounds good. Do you want anything else to be separated as well, such as average current?

**Comment by bkueng** [comment]
Done in https://github.com/PX4/flight_review/commit/a50fd08bd39f96cce8924452428b40dcf525645d

**Comment by sanderux** [comment]
Awesome: https://review.px4.io/plot_app?log=6dff50df-55f1-444f-9989-066f6b737e1b
