### ISSUE TITLE
Access to the private log DB

### ISSUE THREAD

**Issue by mtreml** [PX4/flight_review#58]
Hello guys, 
Thank you for this amazing tool! Is it possible to **access/download the whole public flight log database** (instead of writing a scraper that pulls it)? This would make it easier to experiment with all the timeseries available so far and feed them to some LSTMs etc.

**Comment by bkueng** [comment]
Hi
I was thinking about that already. The logs are stored as ulog files on the server together with an sqllite database. So what I would do is to add a JSON (or similar) interface that lets you retrieve all public logs, which then can be used to download the files. But I don't think I have the time to do that shortly, so I'm happy to accept a PR if you want to do that.

**Comment by bkueng** [comment]
This got implemented in https://github.com/PX4/flight_review/pull/61
