### ISSUE TITLE
Stabilized Mode color error in for Google Map

### ISSUE THREAD

**Issue by Baycken** [PX4/flight_review#65]
The stabilized mode color for the google map is incorrectly shown as purple. 

Here is the altitude graph which correctly shows stabilized mode with blue background:
![Altitude](https://docs.google.com/uc?id=0B17djho2WjKKX1JNWWtJakhDUkU)

Here is the google map view of the log, which show stabilized mode incorrectly as purple:
![Google Map](https://docs.google.com/uc?id=0B17djho2WjKKNktPTmJpX1RnRkU)

And here is the link to the log in question:
https://review.px4.io/plot_app?log=77a2d3d3-1834-40d0-bb0c-61b22aad9214

Here is another log with the same problem:
https://review.px4.io/plot_app?log=80daaa0a-6f12-467d-add2-27599c8fda38

**Comment by bkueng** [comment]
Fixed. This bug got introduced in https://github.com/PX4/flight_review/commit/7a6dd8dd19dfebb58dda2b235e2ea3d5f54996bc and requires to update pyulog (https://github.com/PX4/pyulog/commit/724ba222e3ef2788e0de9b6e7a1dc2315f1b23b8).
