### ISSUE TITLE
'Acceleration Power Spectral Density' doesn't work on high data rate log

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/flight_review#75]
In case of High rate log the Spectral Density fails and this is how the plot looks like:
![image](https://user-images.githubusercontent.com/29940676/33795934-5d2945e8-dcf3-11e7-9447-e74035c1476b.png)

**Comment by bkueng** [comment]
What do you mean by high rate log? Can you provide a log?

FYI @joaeba

**Comment by joaeba** [comment]
It looks like there could be an issue, but it's hard to debug without a test log. I'll have a look at it if you provide one.

**Comment by BazookaJoe1900** [comment]
Sorry for the late replay, here is log produced from the SITL where you can see the issue.
It happens when the SDLG_PROFILE is set to 17 (from the default of 3)
https://logs.px4.io/plot_app?log=357dc188-f02c-4559-8ea3-cd8ebbb600e3
![image](https://user-images.githubusercontent.com/29940676/34294390-fbb1d668-e710-11e7-8f7c-d1060e2ac534.png)

**Comment by joaeba** [comment]
@BazookaJoe1900 ok, thank you. I'll have a look at it.

**Comment by joaeba** [comment]
when I open your log file with pyulog, I find your raw sensor data to be sampled only at about 10 Hz (also noticeable when you zoom into the gyro and acceleration plots), while your attitude data is sampled at about 400 Hz. I assume it's a logging problem or could it also be related to pyulog @bkueng ?

**Comment by BazookaJoe1900** [comment]
@joaeba You right, the default of 3 on SDLOG_PROFILE sets bits 'DEFAULT' and 'ESTIMATOR_REPLAY'
But setting 17 sets 'DEFAULT' and 'HIGH_RATE' (not 'ESTIMATOR_REPLAY').
The Raw data is on 'sensor_combined' message. that is set to Max rate on 'ESTIMATOR_REPLAY' but to 10Hz at 'DEFAULT'. that why the rate of the Raw data rate is low.
I think you can either close the issue or maybe make the spectral look a bit better on that lower rate of Raw data

**Comment by bkueng** [comment]
PR got merged. In addition, I added `sensor_combined` to the high rate profile in https://github.com/PX4/Firmware/pull/8641/commits/0be70896ae7743689fbdaf78bbf77a7ab7f752d1
