### ISSUE TITLE
Bug: Log Times Can Be Incorrect

### ISSUE THREAD

**Issue by keenanjohnson** [PX4/flight_review#87]
I've noticed that on all of the flight logs I have submitted, the vehicle flight time and units of the plots seem to be incorrect. 

See an example here: https://logs.px4.io/plot_app?log=7c57fa9a-0ee1-4916-80d7-fae18554a8fe

The tool says the flight time is over 3 hours. 
![image](https://user-images.githubusercontent.com/2559382/36524979-f8a9e952-175c-11e8-8004-72d3c56db7f4.png)

This is confirmed by the timing in the plots:

![image](https://user-images.githubusercontent.com/2559382/36525047-3700a40c-175d-11e8-9f12-4cb8f51074e6.png)

As I was the pilot and confirmed by flightplotlib however, the flight time was actually much less than that:

![image](https://user-images.githubusercontent.com/2559382/36525218-d27bd726-175d-11e8-8ddc-32ab55aa8926.png)

It would appear the web tool is treating the minutes like hours.

**Comment by bkueng** [comment]
The Vehicle Flight Time is the vehicle's total flight time.
The plots show the time since boot (which can be useful to know). Note that with FlightPlot you can switch the displayed time as well.
So there is no bug here, but if you have suggestions, I'm open for improvements.

**Comment by keenanjohnson** [comment]
Oh I misunderstood what the total time label was implying.

Is that total flight time for the life of the vehicle or between firmware updates?

Perhaps we could improve the title slightly?

**Comment by bkueng** [comment]
> Is that total flight time for the life of the vehicle or between firmware updates?

It's for the life of the vehicle. Though you can reset it manually if you really wanted to, it's a parameter.

> Perhaps we could improve the title slightly?

Sure, what do you suggest? It should be something short though. Maybe with a tooltip if needed.

**Comment by keenanjohnson** [comment]
Maybe it could be "Vehicle Life Flight Time"?

**Comment by bkueng** [comment]
Ok, updated in https://github.com/PX4/flight_review/commit/6cc3d8855f7f60a11c1ccfe04d4b899ed4a792de

**Comment by keenanjohnson** [comment]
Thanks!
