### ISSUE TITLE
Upload form no file path and strange indentation

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/flight_review#93]
Recently when I want to upload a log and choose one from my computer the file path doesn't get shown aynmore next to the Browse button so I actually don't know if I already chose one and which.

Also a detail: At least on latest Chrome on Windows there are unexpceted indentations in evey text field of the upload form and I ended up trying to delete a non-existing space because it looks like there is one.

Here's a screenshot (I chose a file before):
![upload_form](https://user-images.githubusercontent.com/4668506/37346925-f434c4ea-26d0-11e8-9dbf-91f90ef067f3.JPG)

**Comment by bkueng** [comment]
Thanks for paying attention to details. A fix is in https://github.com/PX4/flight_review/pull/94
