### ISSUE TITLE
Pixhawk2.1 hardware is displayed as PX4FMU_V2 instead of PX4FMU_V3

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/flight_review#97]
Problem:
The flight log of Pixhawk2.1 is displayed as 'PX4FMU_V2'.
But it is built by target 'px4fmu-v3_default'.
So I think it should be displayed as 'PX4FMU_V3'.

Thanks a lot for flight review software!

**Comment by bkueng** [comment]
The PX4FMU_V2 refers to the board hardware, which might not be the same as the build target. In fact the px4fmu-v3_default is the same as px4fmu-v2_default, just with more modules enabled (you could flash px4fmu-v2_default on your board). So the displayed board version here is correct.

You're welcome!

**Comment by bigbellmercy** [comment]
Thanks, Beat! That's clear answer.
Jong
