### ISSUE TITLE
Request: Build target display function

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/flight_review#98]
Function:
It would be better that build target is displayed. For example, 'px4fmu-v3_default'.

Reason:
I'd like to sort or search the flight logs for Pixhawk2.1 (px4fmu-v3_default). But I cannot discern them.

Consider it please~

**Comment by bkueng** [comment]
The build target is the wrong information for that. Instead we need the board subtype, which I now added (https://github.com/PX4/Firmware/pull/9239). But it will only be available in future logs.

**Comment by bigbellmercy** [comment]
Great!
